version: 2
jobs:
  build:
    working_directory: ~/celery-beat/testapp
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD : Password_db
    steps:
      - type: checkout

      - restore_cache:
          key:
          - v1-dependecies-{{ checksum "requirments/requirements.txt" }}
      - run:
          name: 'installing dependencies'
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirments/requirements.txt
      - save_cache:
      paths:
        -./venv
          key:
          - v1-dependecies-{{ checksum "requirments/requirements.txt" }}
          paths:
            - ".venv"

      - run:
          command: |
          . venv/bin/activate
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1