version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/celery-beat
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirments/requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirments/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirments/requirements.txt" }}
          key: deps1-{{ .Branch }}-{{ checksum "requirments/requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

